version: '3.8'

services:
  # Servicio del Frontend (React + Nginx)
  frontend:
    # Usar la imagen ya subida a un registry (GHCR)
    image: ghcr.io/yaircorrea/taskflow-frontend-frontend:latest
    ports:
      # Mapea el puerto 8080 de tu máquina al puerto 80 del contenedor
      - "8080:80"
    restart: always
    depends_on:
      - backend
    networks:
      - taskflow-net

  # Servicio del Backend (Flask + Gunicorn - tu equipo se encarga de su Dockerfile)
  backend:
    # Usar la imagen subida a GHCR (suponiendo que tu compañero la ha subido)
    image: ghcr.io/yaircorrea/taskflow-frontend-backend:latest
    ports:
      # Puertos para la aplicacion via gunicorn y la gui de supervisor respectivamente.
      - "5000:8000"
      - "9001:9001"
    volumes:
      # Monta un volumen para persistir la base de datos SQLite
      - taskflow-db:/app/instance
    restart: always
    networks:
      - taskflow-net
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

# Define la red que usarán los contenedores para comunicarse
networks:
  taskflow-net:
    driver: bridge

# Define el volumen para la base de datos
volumes:
  taskflow-db:
